In [1]:
import scipy
from scipy.cluster.vq import kmeans, vq, whiten

In [2]:
student_scores = [[80] , [78] , [55] , [60] , [62] ,
                [59] , [48] , [49] , [51] , [54] ,
                [72] , [95] , [78] , [54] , [50] ,
                [61] , [57] , [56] , [65] , [53]];

In [47]:
student_scores = whiten(student_scores) # normalize 
centroids ,_ = kmeans(student_scores, 3) # mean calculate algo

In [48]:
student_scores

array([[6.53573177],
       [6.37233848],
       [4.49331559],
       [4.90179883],
       [5.06519213],
       [4.82010218],
       [3.92143906],
       [4.00313571],
       [4.16652901],
       [4.41161895],
       [5.8821586 ],
       [7.76118148],
       [6.37233848],
       [4.41161895],
       [4.08483236],
       [4.98349548],
       [4.65670889],
       [4.57501224],
       [5.31028207],
       [4.3299223 ]])

In [49]:
centroids

array([[4.26638046],
       [4.95626326],
       [6.58474976]])

In [50]:
result ,_ = vq(student_scores, centroids)

In [51]:
# seem result is telling no. group of each in student scores
result

array([2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 1, 0, 1, 0])

In [52]:
result.reshape(4, 5) # group 1 is bigger than group 0

array([[2, 2, 0, 1, 1],
       [1, 0, 0, 0, 0],
       [2, 2, 2, 0, 0],
       [1, 1, 0, 1, 0]])

In [54]:
import scipy.constants
print ("The PI is %.16f"% scipy.constants.pi)
print ("The speed of light is c = %.1F"% scipy.constants.c)
print ("The newton ’s gravity constant is G = %.1f"% scipy.constants.g)
# well known maths/physics constant

The PI is 3.1415926535897931
The speed of light is c = 299792458.0
The newton ’s gravity constant is G = 9.8


In [ ]:
# seem its find all dictionary keys of physcial_constants that has the string
scipy.constants.find("gram")

In [21]:
print(scipy.constants.physical_constants["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


In [22]:
# my mass is 55 kg
m = 55

In [23]:
e = m * scipy.constants.c ** 2

In [24]:
e

4.943153483052497e+18

In [28]:
import scipy.stats as stats
import numpy as np


In [29]:
x = np.array([19 ,18 ,21 ,16 ,15 ,17 ,20 ,18]) ;
print(stats.tmin(x), stats.tmax(x), stats.tmean(x), stats.tvar(x)) ;

15 21 18.0 4.0


In [30]:
print(stats.describe(x));

DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


In [31]:
student_scores = [[80] , [78] , [55] , [60] , [62] ,
                [59] , [48] , [49] , [51] , [54] ,
                [72] , [95] , [78] , [54] , [50] ,
                [61] , [57] , [56] , [65] , [53]];
print(stats.tmean(student_scores)) # mean
print(stats.tstd(student_scores)) # sample std
print((62 - stats.tmean(student_scores))/stats.tstd(student_scores)) # z score


61.85
[12.55838994]
[0.01194421]


In [33]:
student_scores = np.array(student_scores)

In [36]:
z_all = (student_scores - stats.tmean(student_scores))/stats.tstd(student_scores)

In [38]:
z_all

array([[ 1.44524896],
       [ 1.28599288],
       [-0.54545209],
       [-0.14731188],
       [ 0.01194421],
       [-0.22693992],
       [-1.10284838],
       [-1.02322034],
       [-0.86396425],
       [-0.62508013],
       [ 0.80822462],
       [ 2.63966959],
       [ 1.28599288],
       [-0.62508013],
       [-0.9435923 ],
       [-0.06768384],
       [-0.386196  ],
       [-0.46582404],
       [ 0.25082833],
       [-0.70470817]])