## 1. Find out whether a matrix is a diagonal matrix.  (First check whether the matrix is a square matrix and then check whether the non diagonal elements are zeroes).

In [1]:
import numpy as np

In [6]:
def check_diag(m):
    shape = m.shape
    # check rank 2 and square matrix
    if len(shape) == 2 and shape[0] == shape[1]:
        for i in range(shape[0]):
            for j in range(i):
                if m[i, j] != 0 and m[j, i] != 0:
                    return False
        return True
    return False

In [7]:
# slower for small m
def check_diag_v2(m):
    shape = m.shape
    return len(shape) == 2 and shape[0] == shape[1] and np.sum(np.abs(m)) == np.sum(np.abs(m.diagonal()))

In [8]:
def __check_diag_v3(m, i, j):
    if j == m.shape[1]:
        return __check_diag_v3(m, i+1, 0)
    if i == m.shape[0]-1 and j == m.shape[1]-1:
        return True
    if i == j:
        return __check_diag_v3(m, i, j+1)
    if m[i, j] != 0:
        return False
    return __check_diag_v3(m, i, j+1)
    

def check_diag_v3(m):
    shape = m.shape
    return len(shape) == 2 and shape[0] == shape[1] and __check_diag_v3(m, 0, 0)

In [9]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [10]:
check_diag_v3(m)

False

In [11]:
t = np.diag(range(50))
t

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [12]:
check_diag_v3(t)

True

In [13]:
%timeit check_diag(m)

The slowest run took 5.38 times longer than the fastest. This could mean that an intermediate result is being cached.
2.48 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit check_diag_v2(m)

12.7 µs ± 729 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%timeit check_diag_v3(m)

1.53 µs ± 65.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit check_diag(t)

381 µs ± 12.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit check_diag_v2(t)

16.6 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
%timeit check_diag_v3(m)

1.59 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## 2. Find out whether a matrix is a skew-symmetric matrix.  (First check whether the matrix is a square matrix and then check whether a_ij = - a_ji)

In [26]:
def check_skew_sym(m):
    shape = m.shape
    if len(shape) == 2 and shape[0] == shape[1]:
        for i in range(shape[0]):
            for j in range(i):
                if m[i, j] != -m[j, i]:
                    return False
        return True
    return False

In [32]:
def __check_skew_sym_v3(m, i, j):
    if i == m.shape[0]-1 and j == m.shape[1]-1:
        return True
    if i == j:
        return __check_skew_sym_v3(m, i+1, 0)
    if m[i, j] != -m[j, i]:
        return False
    return __check_skew_sym_v3(m, i, j+1)
    

def check_skew_sym_v3(m):
    shape = m.shape
    return len(shape) == 2 and shape[0] == shape[1] and __check_skew_sym_v3(m, 0, 0)

In [96]:
m = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 8, 9]
])
m

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [97]:
check_skew_sym(m)

False

In [98]:
check_skew_sym_v3(m)

False

In [99]:
a = np.array([
    [4, 2, -1],
    [-2, 1, 0],
    [1, 0, 10]
])
a

array([[ 4,  2, -1],
       [-2,  1,  0],
       [ 1,  0, 10]])

In [100]:
check_skew_sym(a)

True

In [101]:
check_skew_sym_v3(a)

True

In [102]:
%timeit check_skew_sym(m)

1.37 µs ± 38.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [103]:
%timeit check_skew_sym_v3(m)

1.47 µs ± 55.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [104]:
%timeit check_skew_sym(a)

2.37 µs ± 84.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [105]:
%timeit check_skew_sym_v3(a)

3.83 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 3. Find an inverse of a matrix by finding its determinant, minor, cofactor and adjugate.

In [27]:
def det(m: np.ndarray):
    global det_count
    if m.shape[0] == 1:
        det_count += 1
        return m[0]
    m = np.copy(m)
    reduce_m = np.delete(m, 0, 0)
    s = 0
    for i in range(m.shape[0]):
        n = np.delete(reduce_m, i, 1)
        s += (-1)**(i) * m[0, i] * det(n)
    return s

def minor(m):
    out = np.zeros(m.shape)
    for i in range(m.shape[0]):
        n = np.delete(m.copy(), i, 0)
        for j in range(m.shape[1]):
            p = np.delete(n.copy(), j, 1)
            out[i, j] = det(p)
    return out

def cofactor(m):
    out = np.zeros(m.shape)
    for i in range(m.shape[0]):
        n = np.delete(m.copy(), i, 0)
        for j in range(m.shape[1]):
            p = np.delete(n.copy(), j, 1)
            out[i, j] = (-1)**(i + j) * det(p)
    return out

def adjoint(m):
    return cofactor(m).T

def inverse_matmul(m):
    if len(m.shape) != 2 or m.shape[0] != m.shape[1]:
        raise Exception("input matrix is not sqaure or not in rank 2")
    d = det(m)
    if d == 0:
        raise Exception("determinant of input matrix is zero, m is not invertable (singular)")
    adj = adjoint(m)
    return adj/d
    

In [107]:
inverse_matmul(a)

array([[ 0.12345679, -0.24691358,  0.01234568],
       [ 0.24691358,  0.50617284,  0.02469136],
       [-0.01234568,  0.02469136,  0.09876543]])

In [108]:
np.linalg.inv(a)

array([[ 0.12345679, -0.24691358,  0.01234568],
       [ 0.24691358,  0.50617284,  0.02469136],
       [-0.01234568,  0.02469136,  0.09876543]])

In [111]:
inverse_matmul(m)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [112]:
np.linalg.inv(m)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [5]:
m = np.array([
    [3, -2, 2, -1],
    [2, 1, -2, 1],
    [1, -2, 2, 5],
    [-2, 4, 1, 3]
], dtype="float64")

In [6]:

adjoint(m)

array([[-61., -60.,   7., -12.],
       [-33., -28.,  35., -60.],
       [-65.,  52.,   3., -44.],
       [ 25., -20., -43.,  -4.]])

In [28]:
det_count = 0


In [29]:
inverse_matmul(m)

array([[ 0.22426471,  0.22058824, -0.02573529,  0.04411765],
       [ 0.12132353,  0.10294118, -0.12867647,  0.22058824],
       [ 0.23897059, -0.19117647, -0.01102941,  0.16176471],
       [-0.09191176,  0.07352941,  0.15808824,  0.01470588]])

In [30]:
det_count

120

In [31]:
np.linalg.inv(m)

array([[ 0.22426471,  0.22058824, -0.02573529,  0.04411765],
       [ 0.12132353,  0.10294118, -0.12867647,  0.22058824],
       [ 0.23897059, -0.19117647, -0.01102941,  0.16176471],
       [-0.09191176,  0.07352941,  0.15808824,  0.01470588]])

In [32]:
m = np.array([
    [3, -2, 2],
    [1, -2, 2],
    [-2, 4, 1]
])
det(m)

array([-20])